[package]
name = "iron-json-response"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>"]

[features]
serde_type = ["serde", "serde_json"]
rustc_serialize_type = ["rustc-serialize"]

[dependencies]
iron = "^0.3.0"
mime = "^0.2"
rustc-serialize = { version = "^0.3.18", optional = true }
serde = { version = "^0.7.0", optional = true }
serde_json = { version = "^0.7.0", optional = true }
plugin = "^0.2.6"
